id: 1
pretrained: Null
model:
    name:                       MaskRCNN_ResNet50_FPN
    args:
        nclasses:               2

optimizer:
    name:                       SGD
    args:
        lr:                     0.005
        momentum:               0.9
        weight_decay:           0.0005
loss:
    name:                       DiceLoss
    args:
metric:
    -   name:                   PixelAccuracy
        args:                     
            nclasses:           2

scheduler:
    name:                       CosineAnnealingLR
    args:
        T_max:                  761        
dataset:
    train:
        name: data_raw
        args:
            data_root_dir:      /home/ken/ppnckh/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           True  
        loader:
            name: data_loader
            args:
                batch_size:     2
                shuffle:        True
    val:
        name: data_raw
        args:
            data_root_dir:      /home/ken/ppnckh/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           False  
        loader:
            name: data_loader
            args:
                batch_size:     2
                shuffle:        True
trainer: 
    nepochs: 10
    cp_dir: /home/ken/ppnckh/ppnckh/cp/
    val_step: 1
    log_step: 1
