id: 1
pretrained: Null
model:
    name:                       ResidUNet
    args:
        nclasses:               2
        in_channels:            4
optimizer:
    name:                       Adam
    args:
        lr:                     0.01
loss:
    name:                       DiceLoss
    args:
metric:
    -   name:                   DiceScore
        args:                     
            nclasses:           2
    -   name:                   PixelAccuracy
        args:                     
            nclasses:           2
    -   name:                   MeanIoU
        args:                     
            nclasses:           2
scheduler:
    name:                       CosineAnnealingLR
    args:
        T_max:                  761        
dataset:
    train:
        name: data_pose
        args:
            data_root_dir:      /home/ken/ppnckh/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/      
            train_pose_dir:          train_pose/
            val_pose_dir:            val_pose/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           True  
        loader:
            name: data_loader
            args:
                batch_size:     5
                shuffle:        True
    val:
        name: data_pose
        args:
            data_root_dir:      /home/ken/ppnckh/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/ 
            train_pose_dir:          train_pose/
            val_pose_dir:            val_pose/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           False  
        loader:
            name: data_loader
            args:
                batch_size:     5
                shuffle:        True
trainer: 
    nepochs: 10
    cp_dir: /home/ken/ppnckh/ppnckh/cp/
    val_step: 1
    log_step: 1
