unet_local copyid: 1
pretrained: Null
model:
    name:                       EfficientUNet
    args:
        nclasses:               2
        in_channels:            3
        version:                b0
optimizer:
    name:                       Adam
    args:
        lr:                     0.01
loss:
    name:                       DiceLoss
    args:
metric:
    -   name:                   PixelAccuracy
        args:                     
            nclasses:           2

scheduler:
    name:                       CosineAnnealingLR
    args:
        T_max:                  761        
dataset:
    train:
        name: data_raw
        args:
            data_root_dir:      /content/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           True  
        loader:
            name: data_loader
            args:
                batch_size:     32
                shuffle:        True
    val:
        name: data_raw
        args:
            data_root_dir:      /content/ppnckh/src/data/         
            train_dir:          train_image/
            val_dir:            val_image/
            annotation_train_dir:      train_segmentation/ 
            annotation_val_dir:        val_segmentation/  
            is_train:           False  
        loader:
            name: data_loader
            args:
                batch_size:     32
                shuffle:        True
trainer: 
    nepochs: 10
    cp_dir: /content/ppnckh/cp/
    val_step: 1
    log_step: 1
